modLoader = "javafml"
loaderVersion = "[34,)"
issueTrackerURL = "${github}"
license = "GPLv3"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
authors = "LizardOfOz"
description = "${mod_description}"
logoFile = "icon.png"
displayURL="${github}"

[[dependencies.searchlight]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.searchlight]]
modId = "forge"
mandatory = true
versionRange = "[32,)"
ordering = "NONE"
side = "BOTH"